#! /usr/bin/env python

import sys
import os
import re
from distutils import spawn

def docker_ps():
  return os.popen("docker ps").read().split("\n")[1:]

def filter_container(name):
  container_names = [l.split()[-1] for l in docker_ps() if len(l) > 0]
  return [container for container in container_names if re.search(name, container)][0]

def figexec():
  docker = spawn.find_executable("docker")
  container = filter_container(sys.argv[1])
  params = ["docker", "exec", container] + sys.argv[2:]
  os.execv(docker, params)


figexec()
